//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Extension.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeteringCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeteringCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPM.Extension.Web.Resources.MeteringCode", typeof(MeteringCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog.
        /// </summary>
        public static string Analog {
            get {
                return ResourceManager.GetString("Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zählpunktbezeichner.
        /// </summary>
        public static string Col1 {
            get {
                return ResourceManager.GetString("Col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entnahme.
        /// </summary>
        public static string Col10 {
            get {
                return ResourceManager.GetString("Col10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenrückmeldung.
        /// </summary>
        public static string Col11 {
            get {
                return ResourceManager.GetString("Col11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurzbezeichnung.
        /// </summary>
        public static string Col2 {
            get {
                return ResourceManager.GetString("Col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlagentyp.
        /// </summary>
        public static string Col3 {
            get {
                return ResourceManager.GetString("Col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strasse.
        /// </summary>
        public static string Col4 {
            get {
                return ResourceManager.GetString("Col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ.
        /// </summary>
        public static string Col5 {
            get {
                return ResourceManager.GetString("Col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string Col6 {
            get {
                return ResourceManager.GetString("Col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenversand.
        /// </summary>
        public static string Col7 {
            get {
                return ResourceManager.GetString("Col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zählverfahren.
        /// </summary>
        public static string Col8 {
            get {
                return ResourceManager.GetString("Col8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messung.
        /// </summary>
        public static string Col9 {
            get {
                return ResourceManager.GetString("Col9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klimatisierung aktiv.
        /// </summary>
        public static string CoolingActive {
            get {
                return ResourceManager.GetString("CoolingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab2CheckBoxLabel {
            get {
                return ResourceManager.GetString("Tab2CheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab3CheckBoxLabel {
            get {
                return ResourceManager.GetString("Tab3CheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab4CheckBoxLabel {
            get {
                return ResourceManager.GetString("Tab4CheckBoxLabel", resourceCulture);
            }
        }
    }
}
