//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Extension.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeteringCodeThreshold {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeteringCodeThreshold() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPM.Extension.Web.Resources.MeteringCodeThreshold", typeof(MeteringCodeThreshold).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenzwert Bezeichner.
        /// </summary>
        public static string Col1 {
            get {
                return ResourceManager.GetString("Col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisonalitat Anwenden.
        /// </summary>
        public static string Col2 {
            get {
                return ResourceManager.GetString("Col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Global.
        /// </summary>
        public static string Col3 {
            get {
                return ResourceManager.GetString("Col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Global.
        /// </summary>
        public static string Col4 {
            get {
                return ResourceManager.GetString("Col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Sommer.
        /// </summary>
        public static string Col5 {
            get {
                return ResourceManager.GetString("Col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Sommer.
        /// </summary>
        public static string Col6 {
            get {
                return ResourceManager.GetString("Col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Winter.
        /// </summary>
        public static string Col7 {
            get {
                return ResourceManager.GetString("Col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Winter.
        /// </summary>
        public static string Col8 {
            get {
                return ResourceManager.GetString("Col8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig Ab.
        /// </summary>
        public static string Col9 {
            get {
                return ResourceManager.GetString("Col9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenzwerttyp.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenzwerte.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
