//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Extension.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteSpecifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteSpecifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPM.Extension.Web.Resources.SiteSpecifications", typeof(SiteSpecifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heated Area.
        /// </summary>
        public static string BeheizteFläche {
            get {
                return ResourceManager.GetString("BeheizteFläche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Recipient.
        /// </summary>
        public static string EmpfängerFürBerichte {
            get {
                return ResourceManager.GetString("EmpfängerFürBerichte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Gesamtfläche {
            get {
                return ResourceManager.GetString("Gesamtfläche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        public static string KlimatisierungAktivValue {
            get {
                return ResourceManager.GetString("KlimatisierungAktivValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Area.
        /// </summary>
        public static string Nebenfläche {
            get {
                return ResourceManager.GetString("Nebenfläche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Notiz {
            get {
                return ResourceManager.GetString("Notiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Land.
        /// </summary>
        public static string SonstigeFlächen {
            get {
                return ResourceManager.GetString("SonstigeFlächen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Specifications.
        /// </summary>
        public static string Standortspezifkationen {
            get {
                return ResourceManager.GetString("Standortspezifkationen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unheated Area.
        /// </summary>
        public static string UnbeheizteFläche {
            get {
                return ResourceManager.GetString("UnbeheizteFläche", resourceCulture);
            }
        }
    }
}
