//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Extension.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPM.Extension.Model.Resources.CustomerResource", typeof(CustomerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string AccountController_Login_Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("AccountController_Login_Invalid_login_attempt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig Ab.
        /// </summary>
        public static string GultingAb {
            get {
                return ResourceManager.GetString("GultingAb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenzwert Bezeichner.
        /// </summary>
        public static string MeteringPointThreshold_GrenzwertBezeichner_Grenzwert_Bezeichner {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_GrenzwertBezeichner_Grenzwert_Bezeichner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Global.
        /// </summary>
        public static string MeteringPointThreshold_MaximaGlobal_Maxima_Global {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MaximaGlobal_Maxima_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Sommer.
        /// </summary>
        public static string MeteringPointThreshold_MaximaSommer_Maxima_Sommer {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MaximaSommer_Maxima_Sommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxima Winter.
        /// </summary>
        public static string MeteringPointThreshold_MaximaWinter_Maxima_Winter {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MaximaWinter_Maxima_Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Global.
        /// </summary>
        public static string MeteringPointThreshold_MinimaGlobal_Minima_Global {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MinimaGlobal_Minima_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Sommer.
        /// </summary>
        public static string MeteringPointThreshold_MinimaSommer_Minima_Sommer {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MinimaSommer_Minima_Sommer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minima Winter.
        /// </summary>
        public static string MeteringPointThreshold_MinimaWinter_Minima_Winter {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_MinimaWinter_Minima_Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisonalitat Anwenden.
        /// </summary>
        public static string MeteringPointThreshold_SaisonalitatAnwenden_Saisonalitat_Anwenden {
            get {
                return ResourceManager.GetString("MeteringPointThreshold_SaisonalitatAnwenden_Saisonalitat_Anwenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
